server:
  port:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# 普通的键值对
spring:
  profiles:
    active: dev

  mvc:
    static-path-pattern: /**

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    port:
    host:

mybatis-plus:
  mapper-locations:
  configuration:
    map-underscore-to-camel-case:
    lazy-loading-enabled:
    cache-enabled:
    log-impl:
  type-aliases-package:

logging:
  config:
  level:
  file:
    name:
